// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
/*
      gettingStartedSidebar: [
    
        {
          type: 'category',
          label: 'Administrator',
          link: { type: 'doc', id: 'getting-started/Admin/create-account' },
          items: [
            { type: 'doc', id: 'getting-started/Admin/create-account', label: 'Account Pre-reqs' },
            { type: 'doc', id: 'getting-started/Admin/configure-airflow', label: 'Configure Airflow' },
            { type: 'doc', id: 'getting-started/Admin/configure-repository', label: 'Configure Git Repository' },
            { type: 'doc', id: 'getting-started/Admin/configure-repository-using-dbt-coves', label: 'Configure Git Repository Using dbt-coves' },
            { type: 'doc', id: 'getting-started/Admin/creating-airflow-dags', label: 'Creating Airflow Dags' },
            { type: 'doc', id: 'getting-started/Admin/user-management', label: 'User Management' },
          ],
        },
        {
          type: 'category',
          label: 'Developer',
          link: { type: 'doc', id: 'getting-started/developer/snowflake-extension' },
          items: [
            { type: 'doc', id: 'getting-started/developer/snowflake-extension', label: 'Snowflake Extension' },
            { type: 'doc', id: 'getting-started/developer/transform-tab', label: 'Transform Tab' },
            { type: 'doc', id: 'getting-started/developer/working-with-dbt-datacoves', label: 'Working with dbt in Datacoves' },
            { type: 'doc', id: 'getting-started/developer/using-git', label: 'Using Git' },
          ],
        },
    ],

  howToSidebar: [
    {
      type: 'category',
      label: 'How to',
      items: [
        {
          type: 'category',
          label: 'Airflow',
          link: { type: 'doc', id: 'how-tos/airflow/initial-setup' },
          items: [
            { type: 'doc', id: 'how-tos/airflow/initial-setup', label: 'Airflow - Initial setup' },
            { type: 'doc', id: 'how-tos/airflow/use-airflow-api', label: 'Airflow - Accessing the Airflow API' },
            { type: 'doc', id: 'how-tos/airflow/sync-database', label: 'Airflow - Sync Internal Airflow database' },
            { type: 'doc', id: 'how-tos/airflow/api-triggered-dag', label: 'Airflow - Trigger a DAG using Datasets' },
            { type: 'doc', id: 'how-tos/airflow/create-dag-level-docs', label: 'DAGs - Add Dag Documentation' },
            { type: 'doc', id: 'how-tos/airflow/external-python-dag', label: 'DAGs - Calling External Python Scripts' },
            { type: 'doc', id: 'how-tos/airflow/dynamically-set-schedule', label: 'DAGs - Dynamically Set Schedule' },
            { type: 'doc', id: 'how-tos/airflow/generate-dags-from-yml', label: 'DAGs - Generate DAGs from yml' },
            { type: 'doc', id: 'how-tos/airflow/get-current-branch-name', label: 'DAGs - Get Current Git Branch Name from a DAG Task' },
            { type: 'doc', id: 'how-tos/airflow/s3-to-snowflake', label: 'DAGS - Load from S3 to Snowflake' },
            { type: 'doc', id: 'how-tos/airflow/run-adf-pipeline', label: 'DAGs - Run ADF Pipelines' },
            { type: 'doc', id: 'how-tos/airflow/run-airbyte-sync-jobs', label: 'DAGs - Run Airbyte sync jobs' },
            { type: 'doc', id: 'how-tos/airflow/run-dbt', label: 'DAGs - Run dbt' },
            { type: 'doc', id: 'how-tos/airflow/retry-dbt-tasks', label: 'DAGs - Retry dbt jobs' },
            { type: 'doc', id: 'how-tos/airflow/run-databricks-notebook', label: 'DAGs - Run Databricks Notebooks' },
            { type: 'doc', id: 'how-tos/airflow/run-fivetran-sync-jobs', label: 'DAGs - Run Fivetran sync jobs' },
            { type: 'doc', id: 'how-tos/airflow/test-dags', label: 'DAGs - Test DAGs' },
            { type: 'doc', id: 'how-tos/airflow/use-variables-and-connections', label: 'DAGs - Using Variables and Connections' },
            { type: 'doc', id: 'how-tos/airflow/send-emails', label: 'Notifications - Send Emails' },
            { type: 'doc', id: 'how-tos/airflow/send-ms-teams-notifications', label: 'Notifications - Send Microsoft Teams notifications' },
            { type: 'doc', id: 'how-tos/airflow/send-slack-notifications', label: 'Notifications - Send Slack notifications' },
            //{ type: 'doc', id: 'how-tos/airflow/use-aws-secrets-manager', label: 'Secrets - AWS Secrets Manager' },
            { type: 'doc', id: 'how-tos/airflow/use-datacoves-secrets-manager', label: 'Secrets - Datacoves Secrets Manager' },
            { type: 'doc', id: 'how-tos/airflow/customize-worker-environment', label: 'Worker - Custom Worker Environment' },
            { type: 'doc', id: 'how-tos/airflow/request-resources-on-workers', label: 'Worker - Request Memory and CPU' },
          ],
        },
        {
          type: 'category',
          label: 'Datacoves',
          link: { type: 'doc', id: 'how-tos/datacoves/how_to_connection_template' },
          items: [
            { type: 'doc', id: 'how-tos/datacoves/how_to_connection_template', label: 'Configure Connection Templates' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_secrets', label: 'Configure Datacoves Secret' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_environments', label: 'Configure Environments' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_groups', label: 'Configure Groups' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_integrations', label: 'Configure Integrations' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_invitations', label: 'Configure Invitations' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_projects', label: 'Configure Projects' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_configure_aws_secrets_manager', label: 'Configure AWS Secrets Manager' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_configure_azure_DevOps', label: 'Configure Azure DevOps' },
            { type: 'doc', id: 'how-tos/datacoves/create_your_entraid_application', label: 'Create your EntraID App' },
            { type: 'doc', id: 'how-tos/datacoves/add_entraid_app_as_user', label: 'Add EntraID App to DevOps Portal' },
            { type: 'doc', id: 'how-tos/datacoves/gather_azure_devops_auth_details', label: 'Gather DevOps Auth Details' },
            { type: 'doc', id: 'how-tos/datacoves/authenticate_azure_devops', label: 'Authenticate Azure DevOps' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_service_connections', label: 'Configure Service Connections' },
            { type: 'doc', id: 'how-tos/datacoves/how_to_manage_users', label: 'Manage Users' },
            { type: 'doc', id: 'getting-started/Admin/configure-repository', label: 'Update Repository' },
          ],
        },
        {
          type: 'category',
          label: 'Datahub',
          link: { type: 'doc', id: 'how-tos/datahub/how_to_datahub_dbt' },
          items: [
            { type: 'doc', id: 'how-tos/datahub/how_to_datahub_dbt', label: 'Configure dbt metadata ingestion' },
            { type: 'doc', id: 'how-tos/datahub/how_to_datahub_snowflake', label: 'Configure Snowflake metadata ingestion' },
            { type: 'doc', id: 'how-tos/datahub/how_to_datahub_cli', label: 'Manage datahub using CLI' },
          ],
        },
        {
          type: 'category',
          label: 'DataOps',
          link: { type: 'doc', id: 'how-tos/dataops/releasing-new-feature' },
          items: [
            { type: 'doc', id: 'how-tos/dataops/releasing-new-feature', label: 'Releasing a new feature' },
          ],
        },
        {
          type: 'category',
          label: 'dbt',
          link: { type: 'doc', id: 'how-tos/dbt/advenced-dbt-debug' },
          items: [
            { type: 'doc', id: 'how-tos/dbt/advenced-dbt-debug', label: 'Advanced Debugging' },
            { type: 'doc', id: 'how-tos/dbt/compilation-errors', label: 'Compilation Errors' },
            { type: 'doc', id: 'how-tos/dbt/database-errors', label: 'Database Errors' },
            { type: 'doc', id: 'how-tos/dbt/dependency-errors', label: 'Dependency Errors' },
            { type: 'doc', id: 'how-tos/dbt/runtime-errors', label: 'Runtime Errors' },
          ],
        },
        {
          type: 'category',
          label: 'Git',
          link: { type: 'doc', id: 'how-tos/git/ssh-keys' },
          items: [
            { type: 'doc', id: 'how-tos/git/ssh-keys', label: 'SSH Keys configuration' },
          ],
        },
        {
          type: 'category',
          label: 'Metrics & Logs',
          link: { type: 'doc', id: 'how-tos/metrics-and-logs/view-failed-git-sync' },
          items: [
            { type: 'doc', id: 'how-tos/metrics-and-logs/view-failed-git-sync', label: 'Git Sync/S3 Failures' },
          ],
        },
        {
          type: 'category',
          label: 'My Airflow',
          link: { type: 'doc', id: 'how-tos/my_airflow/migrating-service-connections' },
          items: [
            { type: 'doc', id: 'how-tos/my_airflow/migrating-service-connections', label: 'Migrating from Environment Service Connections' },
            { type: 'doc', id: 'how-tos/my_airflow/my-import', label: 'My Import' },
            { type: 'doc', id: 'how-tos/my_airflow/start-my-airflow', label: 'Use My Airflow' },
          ],
        },
        {
          type: 'category',
          label: 'Snowflake',
          link: { type: 'doc', id: 'how-tos/snowflake/snowflake-key-based-auth' },
          items: [
            { type: 'doc', id: 'how-tos/snowflake/snowflake-key-based-auth', label: 'Setting up Snowflake Key-Based Auth' },
            { type: 'doc', id: 'how-tos/snowflake/warehouses-schemas-roles', label: 'Warehouses, Schemas and Roles' },
          ],
        },
              {
          type: 'category',
          label: 'VS Code',
          items: [
            {
              type: 'category',
              label: 'Datacoves Copilot',
              items: [
                {
                  type: 'category',
                  label: 'V1',
                  link: { type: 'doc', id: 'how-tos/vscode/datacoves-copilot/v1' },
                  items: [
                    { type: 'doc', id: 'how-tos/vscode/datacoves-copilot/v1-llm-config', label: 'Config' },
                    { type: 'doc', id: 'how-tos/vscode/datacoves-copilot/v1-llm', label: 'Usage' },
                  ],
                },
                {
                  type: 'category',
                  label: 'V2',
                  link: { type: 'doc', id: 'how-tos/vscode/datacoves-copilot/v2' },
                  items: [
                    { type: 'doc', id: 'how-tos/vscode/datacoves-copilot/v2-llm-config', label: 'Config' },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Initial Configuration',
              items: [
                { type: 'doc', id: 'how-tos/vscode/bigquery_setup', label: 'BigQuery' },
                { type: 'doc', id: 'how-tos/vscode/databricks_setup', label: 'Databricks' },
                { type: 'doc', id: 'how-tos/vscode/redshift_setup', label: 'Redshift' },
                { type: 'doc', id: 'how-tos/vscode/snowflake_setup', label: 'Snowflake' },
              ],
            },
            { type: 'doc', id: 'how-tos/vscode/environment-variables', label: 'Custom Environment Variables' },
            { type: 'doc', id: 'how-tos/vscode/override', label: 'Override VS Code settings' },
            { type: 'doc', id: 'how-tos/vscode/reset-user-env', label: 'Reset User Env' },
            { type: 'doc', id: 'how-tos/vscode/reset-git', label: 'Reset Git' },
          ],
        },
      ],
    },
  ],

  bestPracticesSidebar: [
    {
      type: 'category',
      label: 'Best Practices',
      items: [
        {
          type: 'category',
          label: 'Datacoves',
          items: [
            { type: 'doc', id: 'best-practices/datacoves/folder-structure', label: 'Folder Structure' },
          ],
        },
        {
          type: 'category',
          label: 'dbt',
          items: [
            { type: 'doc', id: 'best-practices/dbt/dbt-guidelines', label: 'dbt Guidelines' },
            { type: 'doc', id: 'best-practices/dbt/object-naming', label: 'Object Naming Standards' },
            { type: 'doc', id: 'best-practices/dbt/inlets-bays-coves', label: 'What are Inlets, Bays, and Coves' },
          ],
        },
      
        {
          type: 'category',
          label: 'Snowflake',
          items: [
            { type: 'doc', id: 'best-practices/snowflake/security-model', label: 'Security Model' },
            { type: 'doc', id: 'best-practices/snowflake/time-travel', label: 'GDPR and Time-Travel' },
          ],
        },
      ],
    },
  ],

  referenceSidebar: [
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Administration Menu',
          items: [
            { type: 'doc', id: 'reference/admin-menu/settings_billing', label: 'Account Settings & Billing' },
            { type: 'doc', id: 'reference/admin-menu/connection_templates', label: 'Connection Templates' },
            { type: 'doc', id: 'reference/admin-menu/environments', label: 'Environments' },
            { type: 'doc', id: 'reference/admin-menu/groups', label: 'Groups' },
            { type: 'doc', id: 'reference/admin-menu/integrations', label: 'Integrations' },
            { type: 'doc', id: 'reference/admin-menu/invitations', label: 'Invitations' },
            { type: 'doc', id: 'reference/admin-menu/projects', label: 'Projects' },
            { type: 'doc', id: 'reference/admin-menu/secrets', label: 'Secrets' },
            { type: 'doc', id: 'reference/admin-menu/service_connections', label: 'Service Connections' },
            { type: 'doc', id: 'reference/admin-menu/users', label: 'Users' },
          ],
        },
        {
          type: 'category',
          label: 'Airflow',
          items: [
            { type: 'doc', id: 'reference/airflow/airflow-best-practices', label: 'Airflow Best Practices' },
            { type: 'doc', id: 'reference/airflow/airflow-config-defaults', label: 'Airflow Config Defaults' },
            { type: 'doc', id: 'reference/airflow/airflow-variables', label: 'Airflow Variables' },
            { type: 'doc', id: 'reference/airflow/dag-generators', label: 'DAG Generators' },
            { type: 'doc', id: 'reference/airflow/datacoves-decorators', label: 'Datacoves Airflow Decorators' },
            { type: 'doc', id: 'reference/airflow/datacoves-commands', label: 'Datacoves CLI Commands' },
            { type: 'doc', id: 'reference/airflow/environment-service-connection-vars', label: 'Datacoves Environment Service Connection Variables' },
            { type: 'doc', id: 'reference/airflow/datacoves-operator', label: 'Datacoves Operators' },
          ],
        },
        {
          type: 'category',
          label: 'Datacoves',
          items: [
            { type: 'doc', id: 'reference/datacoves/versioning', label: 'Versioning' },
            { type: 'doc', id: 'reference/datacoves/vpc-deployment', label: 'VPC Deployment' },
          ],
        },
        {
          type: 'category',
          label: 'Metrics & Logs',
          items: [
            { type: 'doc', id: 'reference/metrics-and-logs/grafana', label: 'Grafana' },
          ],
        },
        { type: 'doc', id: 'reference/security/README', label: 'Security' },
        {
          type: 'category',
          label: 'VS Code',
          items: [
            { type: 'doc', id: 'reference/vscode/csv-in-datacoves', label: 'CSVs' },
            { type: 'doc', id: 'reference/vscode/datacoves-env-vars', label: 'Datacoves Environment Variables' },
            { type: 'doc', id: 'reference/vscode/tips', label: 'VS Code Tips' },
          ],
        },
      ],
    },
  ],

  tutorialsSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        { type: 'link', label: 'Learning Resources', href: 'https://datacoves.com/learning-resources?_gl=1*18cmhau*_ga*MjYwMzYwODE1LjE3NTIyNTAwNDk.*_ga_WFBP8GG4YV*czE3NTYyNDYzMzAkbzUwJGcxJHQxNzU2MjQ2NDg4JGo2MCRsMCRoMA..' },
        { type: 'link', label: 'Educational Data Resources', href: 'https://datacoves.com/data-resources#Educational' },
      ],
    },
  ],*/
};

module.exports = sidebars;